#%RAML 1.0 Trait
types:
  api-status: !include /exchange_modules/88d26fee-1ab8-4462-beb5-0481da09529e/api-status/0.1.3/api-status.raml

heartbeat-response:
  responses:
    200:
      body:
        type: api-status
    400:
      body:
        application/json:
          type: !include /400-response.raml
    401:
      body:
        application/json:
          example: !include /401-response.raml
    403:
      body:
        application/json:
          example: !include /403-response.raml
    500:
      body:
        application/json:
          example: !include /500-response.raml
    503:
      body:
        application/json:
          example: !include /503-response.raml