#%RAML 1.0 DataType
type: object
properties:
  error_namespace:
    description: Error Namespace
    type: string
    example: HTTP, APIKit FILE 
  error_identifier:
    description: Specific type of error in the namespace
    type: string
    example: HTTP:NOT_FOUND, FILE:NOT_FOUND 
  error_description:
    description: A description of the problem.
    type: string
    example: 
  error_detail_description:
    description: A description of the problem, which can be the same or more extensive than the description.
    type: string
    example: 
  error_cause_description:
    description: A description of the cause.
    type: string
    example: 
  error_cause_detail_description:
    description: A description of the cause, which can be the same or more extensive than the description.
    type: string
    example: 
